load-current:
- current: 0.0015
  layer: M2
  x: 1.0
  y: 1.0
- current: 0.0015
  layer: M2
  x: 1.0
  y: 11.0
- current: 0.0015
  layer: M2
  x: 1.0
  y: 21.0
- current: 0.0015
  layer: M2
  x: 1.0
  y: 31.0
- current: 0.0015
  layer: M2
  x: 1.0
  y: 41.0
- current: 0.0015
  layer: M2
  x: 1.0
  y: 51.0
- current: 0.0015
  layer: M2
  x: 1.0
  y: 61.0
- current: 0.0015
  layer: M2
  x: 11.0
  y: 1.0
- current: 0.0015
  layer: M2
  x: 11.0
  y: 11.0
- current: 0.0015
  layer: M2
  x: 11.0
  y: 21.0
- current: 0.0015
  layer: M2
  x: 11.0
  y: 31.0
- current: 0.0015
  layer: M2
  x: 11.0
  y: 41.0
- current: 0.0015
  layer: M2
  x: 11.0
  y: 51.0
- current: 0.0015
  layer: M2
  x: 11.0
  y: 61.0
- current: 0.0015
  layer: M2
  x: 21.0
  y: 1.0
- current: 0.0015
  layer: M2
  x: 21.0
  y: 11.0
- current: 0.0015
  layer: M2
  x: 21.0
  y: 21.0
- current: 0.0015
  layer: M2
  x: 21.0
  y: 31.0
- current: 0.0015
  layer: M2
  x: 21.0
  y: 41.0
- current: 0.0015
  layer: M2
  x: 21.0
  y: 51.0
- current: 0.0015
  layer: M2
  x: 21.0
  y: 61.0
- current: 0.0015
  layer: M2
  x: 31.0
  y: 1.0
- current: 0.0015
  layer: M2
  x: 31.0
  y: 11.0
- current: 0.0015
  layer: M2
  x: 31.0
  y: 21.0
- current: 0.0015
  layer: M2
  x: 31.0
  y: 31.0
- current: 0.0015
  layer: M2
  x: 31.0
  y: 41.0
- current: 0.0015
  layer: M2
  x: 31.0
  y: 51.0
- current: 0.0015
  layer: M2
  x: 31.0
  y: 61.0
- current: 0.0015
  layer: M2
  x: 41.0
  y: 1.0
- current: 0.0015
  layer: M2
  x: 41.0
  y: 11.0
- current: 0.0015
  layer: M2
  x: 41.0
  y: 21.0
- current: 0.0015
  layer: M2
  x: 41.0
  y: 31.0
- current: 0.0015
  layer: M2
  x: 41.0
  y: 41.0
- current: 0.0015
  layer: M2
  x: 41.0
  y: 51.0
- current: 0.0015
  layer: M2
  x: 41.0
  y: 61.0
- current: 0.0015
  layer: M2
  x: 51.0
  y: 1.0
- current: 0.0015
  layer: M2
  x: 51.0
  y: 11.0
- current: 0.0015
  layer: M2
  x: 51.0
  y: 21.0
- current: 0.0015
  layer: M2
  x: 51.0
  y: 31.0
- current: 0.0015
  layer: M2
  x: 51.0
  y: 41.0
- current: 0.0015
  layer: M2
  x: 51.0
  y: 51.0
- current: 0.0015
  layer: M2
  x: 51.0
  y: 61.0
- current: 0.0015
  layer: M2
  x: 61.0
  y: 1.0
- current: 0.0015
  layer: M2
  x: 61.0
  y: 11.0
- current: 0.0015
  layer: M2
  x: 61.0
  y: 21.0
- current: 0.0015
  layer: M2
  x: 61.0
  y: 31.0
- current: 0.0015
  layer: M2
  x: 61.0
  y: 41.0
- current: 0.0015
  layer: M2
  x: 61.0
  y: 51.0
- current: 0.0015
  layer: M2
  x: 61.0
  y: 61.0
pgc-resistor:
- input:
    layer: M3
    x: 1.0
    y: 2.0
  output:
    layer: M2
    x: 1.0
    y: 1.0
  resistance: 13.0
- input:
    layer: M3
    x: 1.0
    y: 22.0
  output:
    layer: M2
    x: 1.0
    y: 21.0
  resistance: 13.0
- input:
    layer: M3
    x: 1.0
    y: 42.0
  output:
    layer: M2
    x: 1.0
    y: 41.0
  resistance: 13.0
- input:
    layer: M3
    x: 1.0
    y: 62.0
  output:
    layer: M2
    x: 1.0
    y: 61.0
  resistance: 13.0
- input:
    layer: M3
    x: 31.0
    y: 12.0
  output:
    layer: M2
    x: 31.0
    y: 11.0
  resistance: 13.0
- input:
    layer: M3
    x: 31.0
    y: 32.0
  output:
    layer: M2
    x: 31.0
    y: 31.0
  resistance: 13.0
- input:
    layer: M3
    x: 31.0
    y: 52.0
  output:
    layer: M2
    x: 31.0
    y: 51.0
  resistance: 13.0
- input:
    layer: M3
    x: 61.0
    y: 2.0
  output:
    layer: M2
    x: 61.0
    y: 1.0
  resistance: 13.0
- input:
    layer: M3
    x: 61.0
    y: 22.0
  output:
    layer: M2
    x: 61.0
    y: 21.0
  resistance: 13.0
- input:
    layer: M3
    x: 61.0
    y: 42.0
  output:
    layer: M2
    x: 61.0
    y: 41.0
  resistance: 13.0
- input:
    layer: M3
    x: 61.0
    y: 62.0
  output:
    layer: M2
    x: 61.0
    y: 61.0
  resistance: 13.0
strap:
- direction: HORIZONTAL
  end: 61.0
  high-end: 65.0
  layer: M2
  low-end: 0.0
  net: VDDV
  start: 1.0
  step: 10.0
  width: 0.5
- direction: VERTICAL
  end: 61.0
  high-end: 65.0
  layer: M3
  low-end: 0.0
  net: VDD
  start: 1.0
  step: 15.0
  width: 0.5
- direction: VERTICAL
  end: 63.0
  high-end: 65.0
  layer: M3
  low-end: 0.0
  net: VDDV
  start: 3.0
  step: 30.0
  width: 0.5
- direction: HORIZONTAL
  end: 61.0
  high-end: 65.0
  layer: M4
  low-end: 0.0
  net: VDD
  start: 1.0
  step: 15.0
  width: 0.5
supply-voltage:
- layer: M4
  voltage: 1.0
  x: 1.0
  y: 1.0
- layer: M4
  voltage: 1.0
  x: 1.0
  y: 16.0
- layer: M4
  voltage: 1.0
  x: 1.0
  y: 31.0
- layer: M4
  voltage: 1.0
  x: 1.0
  y: 46.0
- layer: M4
  voltage: 1.0
  x: 1.0
  y: 61.0
- layer: M4
  voltage: 1.0
  x: 16.0
  y: 1.0
- layer: M4
  voltage: 1.0
  x: 16.0
  y: 16.0
- layer: M4
  voltage: 1.0
  x: 16.0
  y: 31.0
- layer: M4
  voltage: 1.0
  x: 16.0
  y: 46.0
- layer: M4
  voltage: 1.0
  x: 16.0
  y: 61.0
- layer: M4
  voltage: 1.0
  x: 31.0
  y: 1.0
- layer: M4
  voltage: 1.0
  x: 31.0
  y: 16.0
- layer: M4
  voltage: 1.0
  x: 31.0
  y: 31.0
- layer: M4
  voltage: 1.0
  x: 31.0
  y: 46.0
- layer: M4
  voltage: 1.0
  x: 31.0
  y: 61.0
- layer: M4
  voltage: 1.0
  x: 46.0
  y: 1.0
- layer: M4
  voltage: 1.0
  x: 46.0
  y: 16.0
- layer: M4
  voltage: 1.0
  x: 46.0
  y: 31.0
- layer: M4
  voltage: 1.0
  x: 46.0
  y: 46.0
- layer: M4
  voltage: 1.0
  x: 46.0
  y: 61.0
- layer: M4
  voltage: 1.0
  x: 61.0
  y: 1.0
- layer: M4
  voltage: 1.0
  x: 61.0
  y: 16.0
- layer: M4
  voltage: 1.0
  x: 61.0
  y: 31.0
- layer: M4
  voltage: 1.0
  x: 61.0
  y: 46.0
- layer: M4
  voltage: 1.0
  x: 61.0
  y: 61.0
tech:
- name: M2
  rpsq: 0.1
  smin: 0.05
  thickness: 0.095
  type: CONDUCTOR
  wmin: 0.03
- name: M3
  rpsq: 0.1
  smin: 0.06
  thickness: 0.095
  type: CONDUCTOR
  wmin: 0.03
- name: M4
  rpsq: 0.1
  smin: 0.06
  thickness: 0.095
  type: CONDUCTOR
  wmin: 0.03
- area: 0.0025
  from-layer: M3
  name: VIA3
  rpv: 0.5
  to-layer: M4
  type: VIA
- area: 0.0025
  from-layer: M2
  name: VIA2
  rpv: 1.5
  to-layer: M3
  type: VIA
